import {
  CloudHail,
  CookingPot,
  Database,
  Gamepad2,
  Github,
  Home,
  Layers,
  Palette,
  Paperclip,
  QrCode,
  ScrollIcon,
  ShoppingBag,
  TextCursorInput,
  Wallet2,
} from 'lucide-react';

export const SIDEBAR_NAV = [
  { path: '/', label: 'Home', icon: <Home /> },
  { path: '/shopping/home', label: 'Shopping', icon: <ShoppingBag /> },
  {
    path: '/foot-recipes/home',
    label: 'Foot Recipe App',
    icon: <CookingPot />,
    subMenu: true,
    subMenuItems: [{ path: '/foot-recipes/favourites', label: 'Favourites', icon: <CookingPot /> }],
  },
  { path: '/blog/home', label: 'Blog', icon: <Paperclip /> },
  { path: '/my-wallet', label: 'My Wallet', icon: <Wallet2 /> },
  {path: '/hook-form', label: 'Hook Form', icon: <TextCursorInput />},
  { path: '/weather', label: 'Weather App', icon: <CloudHail /> },
  { path: '/find-github', label: 'Find Github', icon: <Github /> },
  { path: '/qr-code', label: 'QR-Code', icon: <QrCode /> },
  { path: '/random-color', label: 'Random Color', icon: <Palette /> },
  { path: '/more-data', label: 'More Data', icon: <Database /> },
  { path: '/tictactoe', label: 'Tic Tac Toe', icon: <Gamepad2 /> },
  { path: '/accordion', label: 'Accordion', icon: <Layers /> },
  { path: '/scroll-indicator', label: 'Scroll Indicator', icon: <ScrollIcon /> },
];
